# Generated by Django 4.2.3 on 2023-08-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudesOPEN311',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin título', max_length=300, verbose_name='Título')),
                ('categoria', models.CharField(default='Sin categoría', max_length=300, verbose_name='Categoría')),
                ('direccion', models.CharField(default='Sin dirección', max_length=300, verbose_name='Dirección')),
                ('descripcion', models.CharField(default='Sin descripción', max_length=300, verbose_name='Descripción general del problema')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/', verbose_name='Archivo adjunto')),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
    ]
